[package]
name = "microservices"
version = "0.1.0"
authors = ["noreflection <a191a191a@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.12"
futures = "0.3.1"
